export type WordPiece = { de: string; pt: string; en: string }

export type CompoundWord = {
  id: string
  part1: WordPiece
  part2: WordPiece
  compound: WordPiece
  /** Word-for-word gloss of the two parts, e.g. "a casa do doente" —
   * the literal image, before the real-world meaning clicks into place. */
  literalPt: string
  literalEn: string
}

export const compoundWords: CompoundWord[] = [
  {
    id: 'krankenhaus',
    part1: { de: 'krank', pt: 'doente', en: 'sick' },
    part2: { de: 'Haus', pt: 'casa', en: 'house' },
    compound: { de: 'Krankenhaus', pt: 'hospital', en: 'hospital' },
    literalPt: 'a casa do doente',
    literalEn: "the sick person's house",
  },
  {
    id: 'krankenwagen',
    part1: { de: 'krank', pt: 'doente', en: 'sick' },
    part2: { de: 'Wagen', pt: 'carro', en: 'car' },
    compound: { de: 'Krankenwagen', pt: 'ambulância', en: 'ambulance' },
    literalPt: 'o carro do doente',
    literalEn: "the sick person's car",
  },
  {
    id: 'flugzeug',
    part1: { de: 'Flug', pt: 'voo', en: 'flight' },
    part2: { de: 'Zeug', pt: 'coisa', en: 'thing' },
    compound: { de: 'Flugzeug', pt: 'avião', en: 'airplane' },
    literalPt: 'coisa de voar',
    literalEn: 'thing for flying',
  },
  {
    id: 'feuerzeug',
    part1: { de: 'Feuer', pt: 'fogo', en: 'fire' },
    part2: { de: 'Zeug', pt: 'coisa', en: 'thing' },
    compound: { de: 'Feuerzeug', pt: 'isqueiro', en: 'lighter' },
    literalPt: 'coisa de fogo',
    literalEn: 'thing for fire',
  },
  {
    id: 'volkswagen',
    part1: { de: 'Volk', pt: 'povo', en: 'people' },
    part2: { de: 'Wagen', pt: 'carro', en: 'car' },
    compound: { de: 'Volkswagen', pt: 'carro do povo', en: "people's car" },
    literalPt: 'o carro do povo',
    literalEn: "the people's car",
  },
  {
    id: 'kindergarten',
    part1: { de: 'Kinder', pt: 'crianças', en: 'children' },
    part2: { de: 'Garten', pt: 'jardim', en: 'garden' },
    compound: { de: 'Kindergarten', pt: 'infantário', en: 'kindergarten' },
    literalPt: 'jardim de crianças',
    literalEn: 'garden of children',
  },
  {
    id: 'biergarten',
    part1: { de: 'Bier', pt: 'cerveja', en: 'beer' },
    part2: { de: 'Garten', pt: 'jardim', en: 'garden' },
    compound: { de: 'Biergarten', pt: 'jardim de cerveja', en: 'beer garden' },
    literalPt: 'jardim de cerveja',
    literalEn: 'beer garden',
  },
  {
    id: 'ampelmann',
    part1: { de: 'Ampel', pt: 'semáforo', en: 'traffic light' },
    part2: { de: 'Mann', pt: 'homem', en: 'man' },
    compound: { de: 'Ampelmann', pt: 'homem do semáforo', en: 'traffic light man' },
    literalPt: 'o homem do semáforo',
    literalEn: 'the traffic light man',
  },
  {
    id: 'schildkroete',
    part1: { de: 'Schild', pt: 'escudo', en: 'shield' },
    part2: { de: 'Kröte', pt: 'sapo', en: 'toad' },
    compound: { de: 'Schildkröte', pt: 'tartaruga', en: 'turtle' },
    literalPt: 'o sapo-escudo',
    literalEn: 'the shield-toad',
  },
  {
    id: 'handschuh',
    part1: { de: 'Hand', pt: 'mão', en: 'hand' },
    part2: { de: 'Schuh', pt: 'sapato', en: 'shoe' },
    compound: { de: 'Handschuh', pt: 'luva', en: 'glove' },
    literalPt: 'o sapato de mão',
    literalEn: 'the hand-shoe',
  },
  {
    id: 'regenschirm',
    part1: { de: 'Regen', pt: 'chuva', en: 'rain' },
    part2: { de: 'Schirm', pt: 'ecrã/proteção', en: 'screen/shield' },
    compound: { de: 'Regenschirm', pt: 'guarda-chuva', en: 'umbrella' },
    literalPt: 'a proteção de chuva',
    literalEn: 'the rain-screen',
  },
  {
    id: 'schneemann',
    part1: { de: 'Schnee', pt: 'neve', en: 'snow' },
    part2: { de: 'Mann', pt: 'homem', en: 'man' },
    compound: { de: 'Schneemann', pt: 'boneco de neve', en: 'snowman' },
    literalPt: 'o homem de neve',
    literalEn: 'the snow-man',
  },
  {
    id: 'fingerhut',
    part1: { de: 'Finger', pt: 'dedo', en: 'finger' },
    part2: { de: 'Hut', pt: 'chapéu', en: 'hat' },
    compound: { de: 'Fingerhut', pt: 'dedal', en: 'thimble' },
    literalPt: 'o chapéu de dedo',
    literalEn: 'the finger-hat',
  },
  {
    id: 'nashorn',
    part1: { de: 'Nase', pt: 'nariz', en: 'nose' },
    part2: { de: 'Horn', pt: 'chifre', en: 'horn' },
    compound: { de: 'Nashorn', pt: 'rinoceronte', en: 'rhino' },
    literalPt: 'o chifre de nariz',
    literalEn: 'the nose-horn',
  },
  {
    id: 'faultier',
    part1: { de: 'faul', pt: 'preguiçoso', en: 'lazy' },
    part2: { de: 'Tier', pt: 'animal', en: 'animal' },
    compound: { de: 'Faultier', pt: 'preguiça (o animal)', en: 'sloth' },
    literalPt: 'o animal preguiçoso',
    literalEn: 'the lazy animal',
  },
  {
    id: 'zahnbuerste',
    part1: { de: 'Zahn', pt: 'dente', en: 'tooth' },
    part2: { de: 'Bürste', pt: 'escova', en: 'brush' },
    compound: { de: 'Zahnbürste', pt: 'escova de dentes', en: 'toothbrush' },
    literalPt: 'a escova de dente',
    literalEn: 'the tooth-brush',
  },
  {
    id: 'eisbaer',
    part1: { de: 'Eis', pt: 'gelo', en: 'ice' },
    part2: { de: 'Bär', pt: 'urso', en: 'bear' },
    compound: { de: 'Eisbär', pt: 'urso polar', en: 'polar bear' },
    literalPt: 'o urso de gelo',
    literalEn: 'the ice-bear',
  },
  {
    id: 'gluehbirne',
    part1: { de: 'glüh', pt: 'brilhar', en: 'glow' },
    part2: { de: 'Birne', pt: 'pera', en: 'pear' },
    compound: { de: 'Glühbirne', pt: 'lâmpada', en: 'lightbulb' },
    literalPt: 'a pera brilhante',
    literalEn: 'the glow-pear',
  },
  {
    id: 'kuehlschrank',
    part1: { de: 'kühl', pt: 'fresco', en: 'cool' },
    part2: { de: 'Schrank', pt: 'armário', en: 'cupboard' },
    compound: { de: 'Kühlschrank', pt: 'frigorífico', en: 'fridge' },
    literalPt: 'o armário fresco',
    literalEn: 'the cool cupboard',
  },
  {
    id: 'wasserfall',
    part1: { de: 'Wasser', pt: 'água', en: 'water' },
    part2: { de: 'Fall', pt: 'queda', en: 'fall' },
    compound: { de: 'Wasserfall', pt: 'cascata', en: 'waterfall' },
    literalPt: 'a queda de água',
    literalEn: 'the water-fall',
  },
  {
    id: 'sonnenblume',
    part1: { de: 'Sonne', pt: 'sol', en: 'sun' },
    part2: { de: 'Blume', pt: 'flor', en: 'flower' },
    compound: { de: 'Sonnenblume', pt: 'girassol', en: 'sunflower' },
    literalPt: 'a flor do sol',
    literalEn: 'the sun-flower',
  },
  {
    id: 'regenbogen',
    part1: { de: 'Regen', pt: 'chuva', en: 'rain' },
    part2: { de: 'Bogen', pt: 'arco', en: 'bow' },
    compound: { de: 'Regenbogen', pt: 'arco-íris', en: 'rainbow' },
    literalPt: 'o arco de chuva',
    literalEn: 'the rain-bow',
  },
  {
    id: 'marienkaefer',
    part1: { de: 'Marien', pt: 'de Maria', en: "Mary's" },
    part2: { de: 'Käfer', pt: 'besouro', en: 'beetle' },
    compound: { de: 'Marienkäfer', pt: 'joaninha', en: 'ladybug' },
    literalPt: 'o besouro de Maria',
    literalEn: "Mary's beetle",
  },
  {
    id: 'fernseher',
    part1: { de: 'fern', pt: 'longe', en: 'far' },
    part2: { de: 'Seher', pt: 'vidente', en: 'seer' },
    compound: { de: 'Fernseher', pt: 'televisão', en: 'television' },
    literalPt: 'o vidente-de-longe',
    literalEn: 'the far-seer',
  },
  {
    id: 'kummerspeck',
    part1: { de: 'Kummer', pt: 'tristeza', en: 'grief' },
    part2: { de: 'Speck', pt: 'toucinho', en: 'bacon' },
    compound: { de: 'Kummerspeck', pt: 'quilos da tristeza', en: 'grief bacon' },
    literalPt: 'o toucinho da tristeza',
    literalEn: 'grief bacon (weight gained from emotional eating)',
  },
  {
    id: 'ohrwurm',
    part1: { de: 'Ohr', pt: 'orelha', en: 'ear' },
    part2: { de: 'Wurm', pt: 'minhoca', en: 'worm' },
    compound: { de: 'Ohrwurm', pt: 'música colada na cabeça', en: 'earworm' },
    literalPt: 'a minhoca da orelha',
    literalEn: 'the ear-worm',
  },
  {
    id: 'nacktschnecke',
    part1: { de: 'nackt', pt: 'nu/nua', en: 'naked' },
    part2: { de: 'Schnecke', pt: 'caracol', en: 'snail' },
    compound: { de: 'Nacktschnecke', pt: 'lesma', en: 'slug' },
    literalPt: 'o caracol nu',
    literalEn: 'the naked snail',
  },
  {
    id: 'stinktier',
    part1: { de: 'stink', pt: 'fede', en: 'stink' },
    part2: { de: 'Tier', pt: 'animal', en: 'animal' },
    compound: { de: 'Stinktier', pt: 'gambá', en: 'skunk' },
    literalPt: 'o animal fedorento',
    literalEn: 'the stink-animal',
  },
  {
    id: 'hexenschuss',
    part1: { de: 'Hexen', pt: 'de bruxa', en: "witch's" },
    part2: { de: 'Schuss', pt: 'tiro', en: 'shot' },
    compound: { de: 'Hexenschuss', pt: 'dor lombar súbita', en: 'lumbago' },
    literalPt: 'o tiro da bruxa',
    literalEn: "the witch's shot",
  },
  {
    id: 'purzelbaum',
    part1: { de: 'purzel', pt: 'tombo', en: 'tumble' },
    part2: { de: 'Baum', pt: 'árvore', en: 'tree' },
    compound: { de: 'Purzelbaum', pt: 'cambalhota', en: 'somersault' },
    literalPt: 'a árvore de tombo',
    literalEn: 'the tumble-tree',
  },
  {
    id: 'schnapsidee',
    part1: { de: 'Schnaps', pt: 'aguardente', en: 'schnapps' },
    part2: { de: 'Idee', pt: 'ideia', en: 'idea' },
    compound: { de: 'Schnapsidee', pt: 'ideia disparatada', en: 'harebrained idea' },
    literalPt: 'a ideia da aguardente',
    literalEn: 'the schnapps-idea',
  },
  {
    id: 'warmduscher',
    part1: { de: 'warm', pt: 'quente', en: 'warm' },
    part2: { de: 'Duscher', pt: 'quem toma duche', en: 'shower-taker' },
    compound: { de: 'Warmduscher', pt: 'fracote (gíria)', en: 'wimp (slang)' },
    literalPt: 'quem toma duche quente',
    literalEn: 'the warm-shower-taker',
  },
  {
    id: 'weltschmerz',
    part1: { de: 'Welt', pt: 'mundo', en: 'world' },
    part2: { de: 'Schmerz', pt: 'dor', en: 'pain' },
    compound: { de: 'Weltschmerz', pt: 'melancolia existencial', en: 'world-weariness' },
    literalPt: 'a dor do mundo',
    literalEn: 'the world-pain',
  },
  {
    id: 'backpfeife',
    part1: { de: 'Back', pt: 'bochecha', en: 'cheek' },
    part2: { de: 'Pfeife', pt: 'apito', en: 'whistle' },
    compound: { de: 'Backpfeife', pt: 'estalo na cara (gíria)', en: 'slap in the face (slang)' },
    literalPt: 'o apito de bochecha',
    literalEn: 'the cheek-whistle',
  },
].sort((a, b) => a.compound.de.localeCompare(b.compound.de, 'de'))
