export type DialogueLine = { speaker: 'a' | 'b'; de: string; pt: string; en: string }
export type Phrase = { de: string; pt: string; en: string }
export type ComprehensionQuestion = { de: string; pt: string; en: string; choices: string[]; correctIndex: number }

export type Scene = {
  id: string
  titleDe: string
  titlePt: string
  titleEn: string
  speakerA: string
  speakerB: string
  lines: DialogueLine[]
  keyPhrases: Phrase[]
  question: ComprehensionQuestion
}

export const scenes: Scene[] = [
  {
    id: 'baeckerei',
    titleDe: 'Bäckerei',
    titlePt: 'Padaria',
    titleEn: 'Bakery',
    speakerA: 'Verkäufer',
    speakerB: 'Kunde',
    lines: [
      { speaker: 'a', de: 'Guten Tag! Was darf es sein?', pt: 'Bom dia! O que vai ser?', en: 'Good day! What can I get you?' },
      { speaker: 'b', de: 'Guten Tag! Ich hätte gern zwei Brötchen.', pt: 'Bom dia! Queria dois pãezinhos.', en: "Hello! I'd like two bread rolls." },
      { speaker: 'a', de: 'Gerne. Sonst noch etwas?', pt: 'Com certeza. Mais alguma coisa?', en: 'Sure. Anything else?' },
      { speaker: 'b', de: 'Ja, ein Vollkornbrot, bitte.', pt: 'Sim, um pão integral, por favor.', en: 'Yes, a wholegrain bread, please.' },
      { speaker: 'a', de: 'Das macht zusammen fünf Euro fünfzig.', pt: 'Isso dá cinco euros e cinquenta ao todo.', en: "That's five euros fifty altogether." },
      { speaker: 'b', de: 'Hier, bitte. Einen schönen Tag noch!', pt: 'Aqui está. Tenha um bom dia!', en: 'Here you go. Have a nice day!' },
      { speaker: 'a', de: 'Danke, ebenfalls!', pt: 'Obrigado, igualmente!', en: 'Thanks, you too!' },
    ],
    keyPhrases: [
      { de: 'Ich hätte gern...', pt: 'Eu queria...', en: 'I would like...' },
      { de: 'Was darf es sein?', pt: 'O que vai ser?', en: 'What can I get you?' },
      { de: 'Sonst noch etwas?', pt: 'Mais alguma coisa?', en: 'Anything else?' },
      { de: 'Das macht ... Euro.', pt: 'Isso dá ... euros.', en: 'That comes to ... euros.' },
      { de: 'das Brötchen / das Brot', pt: 'o pãozinho / o pão', en: 'the bread roll / the bread' },
    ],
    question: {
      de: 'Was kauft der Kunde?',
      pt: 'O que compra o cliente?',
      en: 'What does the customer buy?',
      choices: ['Brötchen und ein Vollkornbrot', 'Nur Kuchen', 'Einen Kaffee', 'Zwei Kuchen'],
      correctIndex: 0,
    },
  },
  {
    id: 'friseur',
    titleDe: 'Friseur',
    titlePt: 'Cabeleireiro',
    titleEn: 'Hairdresser',
    speakerA: 'Friseurin',
    speakerB: 'Kundin',
    lines: [
      { speaker: 'a', de: 'Hallo! Was möchten Sie heute?', pt: 'Olá! O que deseja hoje?', en: 'Hi! What would you like today?' },
      { speaker: 'b', de: 'Ich möchte einen Haarschnitt, bitte.', pt: 'Queria cortar o cabelo, por favor.', en: "I'd like a haircut, please." },
      { speaker: 'a', de: 'Wie kurz soll es sein?', pt: 'Quão curto deve ficar?', en: 'How short should it be?' },
      { speaker: 'b', de: 'Nur die Spitzen, bitte.', pt: 'Só as pontas, por favor.', en: 'Just the tips, please.' },
      { speaker: 'a', de: 'Möchten Sie auch eine neue Farbe?', pt: 'Também quer uma cor nova?', en: 'Would you also like a new color?' },
      { speaker: 'b', de: 'Nein danke, nur schneiden.', pt: 'Não, obrigada, só cortar.', en: 'No thanks, just a cut.' },
      { speaker: 'a', de: 'Alles klar, setzen Sie sich bitte.', pt: 'Perfeito, sente-se, por favor.', en: 'Alright, please sit down.' },
    ],
    keyPhrases: [
      { de: 'Ich möchte einen Haarschnitt.', pt: 'Queria cortar o cabelo.', en: "I'd like a haircut." },
      { de: 'Nur die Spitzen.', pt: 'Só as pontas.', en: 'Just the tips.' },
      { de: 'Wie kurz soll es sein?', pt: 'Quão curto deve ficar?', en: 'How short should it be?' },
      { de: 'Setzen Sie sich bitte.', pt: 'Sente-se, por favor.', en: 'Please sit down.' },
      { de: 'eine neue Farbe', pt: 'uma cor nova', en: 'a new color' },
    ],
    question: {
      de: 'Was möchte die Kundin?',
      pt: 'O que quer a cliente?',
      en: 'What does the customer want?',
      choices: ['Nur die Spitzen schneiden', 'Eine neue Farbe', 'Lange Haare', 'Eine Dauerwelle'],
      correctIndex: 0,
    },
  },
  {
    id: 'supermarkt',
    titleDe: 'Supermarkt',
    titlePt: 'Supermercado',
    titleEn: 'Supermarket',
    speakerA: 'Kassiererin',
    speakerB: 'Kunde',
    lines: [
      { speaker: 'a', de: 'Guten Tag, haben Sie eine Kundenkarte?', pt: 'Bom dia, tem cartão de cliente?', en: 'Hello, do you have a loyalty card?' },
      { speaker: 'b', de: 'Nein, ich habe keine.', pt: 'Não, não tenho.', en: "No, I don't have one." },
      { speaker: 'a', de: 'Kein Problem. Das macht zwölf Euro dreißig.', pt: 'Sem problema. Isso dá doze euros e trinta.', en: "No problem. That's twelve euros thirty." },
      { speaker: 'b', de: 'Kann ich mit Karte zahlen?', pt: 'Posso pagar com cartão?', en: 'Can I pay by card?' },
      { speaker: 'a', de: 'Ja, natürlich.', pt: 'Sim, claro.', en: 'Yes, of course.' },
      { speaker: 'b', de: 'Brauche ich eine Tüte?', pt: 'Preciso de um saco?', en: 'Do I need a bag?' },
      { speaker: 'a', de: 'Die kostet zwanzig Cent extra.', pt: 'Esse custa mais vinte cêntimos.', en: 'That costs 20 cents extra.' },
      { speaker: 'b', de: 'Gut, eine Tüte bitte. Und ich brauche eine Rechnung für meine Firma.', pt: 'Está bem, um saco, por favor. E preciso de uma fatura para a minha empresa.', en: 'OK, one bag please. And I need an invoice for my company.' },
      { speaker: 'a', de: 'Natürlich, kein Problem. Hier ist Ihre Rechnung.', pt: 'Claro, sem problema. Aqui está a sua fatura.', en: "Of course, no problem. Here's your invoice." },
      { speaker: 'b', de: 'Vielen Dank! Auf Wiedersehen!', pt: 'Muito obrigado! Adeus!', en: 'Thank you very much! Goodbye!' },
    ],
    keyPhrases: [
      { de: 'Haben Sie eine Kundenkarte?', pt: 'Tem cartão de cliente?', en: 'Do you have a loyalty card?' },
      { de: 'Kann ich mit Karte zahlen?', pt: 'Posso pagar com cartão?', en: 'Can I pay by card?' },
      { de: 'Brauche ich eine Tüte?', pt: 'Preciso de um saco?', en: 'Do I need a bag?' },
      { de: 'Das macht ... Euro.', pt: 'Isso dá ... euros.', en: "That's ... euros." },
      { de: 'Ich brauche eine Rechnung für meine Firma.', pt: 'Preciso de uma fatura para a minha empresa.', en: 'I need an invoice for my company.' },
    ],
    question: {
      de: 'Wie zahlt der Kunde?',
      pt: 'Como paga o cliente?',
      en: 'How does the customer pay?',
      choices: ['Mit Karte', 'Bar', 'Mit dem Handy', 'Er zahlt nicht'],
      correctIndex: 0,
    },
  },
  {
    id: 'restaurant',
    titleDe: 'Restaurant',
    titlePt: 'Restaurante',
    titleEn: 'Restaurant',
    speakerA: 'Kellner',
    speakerB: 'Gast',
    lines: [
      { speaker: 'a', de: 'Guten Abend! Haben Sie schon gewählt?', pt: 'Boa noite! Já escolheu?', en: 'Good evening! Have you chosen already?' },
      { speaker: 'b', de: 'Ja, ich hätte gern die Suppe und den Fisch.', pt: 'Sim, queria a sopa e o peixe.', en: "Yes, I'd like the soup and the fish." },
      { speaker: 'a', de: 'Und zu trinken?', pt: 'E para beber?', en: 'And to drink?' },
      { speaker: 'b', de: 'Ein Glas Wasser, bitte.', pt: 'Um copo de água, por favor.', en: 'A glass of water, please.' },
      { speaker: 'a', de: 'Kommt sofort.', pt: 'Já vem.', en: 'Coming right up.' },
      { speaker: 'b', de: 'Die Rechnung, bitte.', pt: 'A conta, por favor.', en: 'The bill, please.' },
      { speaker: 'a', de: 'Zusammen oder getrennt?', pt: 'Junto ou separado?', en: 'Together or separate?' },
      { speaker: 'b', de: 'Zusammen, bitte. Und ich brauche eine Rechnung für die Firma.', pt: 'Junto, por favor. E preciso de uma fatura para a empresa.', en: 'Together, please. And I need an invoice for my company.' },
      { speaker: 'a', de: 'Kein Problem, das mache ich. Das macht dann fünfundzwanzig Euro.', pt: 'Sem problema, eu trato disso. Isso dá então vinte e cinco euros.', en: 'No problem, I\'ll take care of that. That comes to twenty-five euros then.' },
      { speaker: 'b', de: 'Hier, bitte. Der Rest ist für Sie.', pt: 'Aqui está. O troco é para si.', en: 'Here you go. Keep the change.' },
      { speaker: 'a', de: 'Vielen Dank! Hier ist Ihre Rechnung. Einen schönen Abend noch!', pt: 'Muito obrigado! Aqui está a sua fatura. Tenha uma boa noite!', en: "Thank you very much! Here's your invoice. Have a nice evening!" },
      { speaker: 'b', de: 'Danke, Ihnen auch! Auf Wiedersehen!', pt: 'Obrigado, igualmente! Adeus!', en: 'Thanks, you too! Goodbye!' },
    ],
    keyPhrases: [
      { de: 'Ich hätte gern...', pt: 'Eu queria...', en: 'I would like...' },
      { de: 'Die Rechnung, bitte.', pt: 'A conta, por favor.', en: 'The bill, please.' },
      { de: 'Ich brauche eine Rechnung für die Firma.', pt: 'Preciso de uma fatura para a empresa.', en: 'I need an invoice for my company.' },
      { de: 'Zusammen oder getrennt?', pt: 'Junto ou separado?', en: 'Together or separate?' },
      { de: 'Der Rest ist für Sie.', pt: 'O troco é para si.', en: 'Keep the change.' },
    ],
    question: {
      de: 'Was möchte der Gast trinken?',
      pt: 'O que quer beber o cliente?',
      en: 'What does the guest want to drink?',
      choices: ['Ein Glas Wasser', 'Ein Bier', 'Einen Kaffee', 'Einen Wein'],
      correctIndex: 0,
    },
  },
  {
    id: 'bahnhof',
    titleDe: 'Bahnhof',
    titlePt: 'Estação de comboios',
    titleEn: 'Train station',
    speakerA: 'Angestellter',
    speakerB: 'Reisender',
    lines: [
      { speaker: 'a', de: 'Guten Tag, wie kann ich helfen?', pt: 'Bom dia, como posso ajudar?', en: 'Hello, how can I help?' },
      { speaker: 'b', de: 'Ich brauche eine Fahrkarte nach München.', pt: 'Preciso de um bilhete para Munique.', en: 'I need a ticket to Munich.' },
      { speaker: 'a', de: 'Einfach oder hin und zurück?', pt: 'Ida ou ida e volta?', en: 'One-way or round trip?' },
      { speaker: 'b', de: 'Hin und zurück, bitte.', pt: 'Ida e volta, por favor.', en: 'Round trip, please.' },
      { speaker: 'a', de: 'Wann möchten Sie fahren?', pt: 'Quando quer viajar?', en: 'When do you want to travel?' },
      { speaker: 'b', de: 'Heute Nachmittag.', pt: 'Esta tarde.', en: 'This afternoon.' },
      { speaker: 'a', de: 'Der nächste Zug fährt um 15 Uhr, Gleis 4.', pt: 'O próximo comboio parte às 15h, linha 4.', en: 'The next train leaves at 3pm, platform 4.' },
      { speaker: 'b', de: 'Vielen Dank!', pt: 'Muito obrigado!', en: 'Thank you very much!' },
    ],
    keyPhrases: [
      { de: 'Ich brauche eine Fahrkarte nach...', pt: 'Preciso de um bilhete para...', en: 'I need a ticket to...' },
      { de: 'Einfach oder hin und zurück?', pt: 'Ida ou ida e volta?', en: 'One-way or round trip?' },
      { de: 'Wann fährt der nächste Zug?', pt: 'Quando parte o próximo comboio?', en: 'When does the next train leave?' },
      { de: 'Von welchem Gleis?', pt: 'De que linha?', en: 'From which platform?' },
      { de: 'Der Zug hat Verspätung.', pt: 'O comboio está atrasado.', en: 'The train is delayed.' },
    ],
    question: {
      de: 'Von welchem Gleis fährt der Zug?',
      pt: 'De que linha parte o comboio?',
      en: 'Which platform does the train leave from?',
      choices: ['Gleis 4', 'Gleis 1', 'Gleis 7', 'Gleis 12'],
      correctIndex: 0,
    },
  },
  {
    id: 'kennenlernen',
    titleDe: 'Kennenlernen',
    titlePt: 'Conhecer alguém',
    titleEn: 'Getting to know someone',
    speakerA: 'Lisa',
    speakerB: 'Tom',
    lines: [
      { speaker: 'a', de: 'Hallo! Ich bin Lisa. Wie heißt du?', pt: 'Olá! Eu sou a Lisa. Como te chamas?', en: "Hi! I'm Lisa. What's your name?" },
      { speaker: 'b', de: 'Ich heiße Tom. Freut mich!', pt: 'Chamo-me Tom. Prazer!', en: "I'm Tom. Nice to meet you!" },
      { speaker: 'a', de: 'Freut mich auch! Wie alt bist du?', pt: 'Igualmente! Quantos anos tens?', en: 'Nice to meet you too! How old are you?' },
      { speaker: 'b', de: 'Ich bin achtundzwanzig. Und du?', pt: 'Tenho vinte e oito. E tu?', en: "I'm twenty-eight. And you?" },
      { speaker: 'a', de: 'Ich bin dreißig. Woher kommst du?', pt: 'Eu tenho trinta. De onde vens?', en: "I'm thirty. Where are you from?" },
      { speaker: 'b', de: 'Ich komme aus Portugal, aber ich wohne jetzt in Berlin. Und du?', pt: 'Venho de Portugal, mas moro agora em Berlim. E tu?', en: "I'm from Portugal, but I live in Berlin now. And you?" },
      { speaker: 'a', de: 'Ich komme aus München. Was machst du beruflich?', pt: 'Eu venho de Munique. O que fazes profissionalmente?', en: "I'm from Munich. What do you do for work?" },
      { speaker: 'b', de: 'Ich arbeite als Ingenieur. Was machst du gern in deiner Freizeit?', pt: 'Trabalho como engenheiro. O que gostas de fazer nos teus tempos livres?', en: 'I work as an engineer. What do you like doing in your free time?' },
      { speaker: 'a', de: 'Ich spiele gern Tennis und lese viel. Das war schön, dich kennenzulernen!', pt: 'Gosto de jogar ténis e de ler muito. Foi um prazer conhecer-te!', en: 'I like playing tennis and reading a lot. It was nice meeting you!' },
    ],
    keyPhrases: [
      { de: 'Wie heißt du?', pt: 'Como te chamas?', en: "What's your name?" },
      { de: 'Wie alt bist du?', pt: 'Quantos anos tens?', en: 'How old are you?' },
      { de: 'Woher kommst du?', pt: 'De onde vens?', en: 'Where are you from?' },
      { de: 'Was machst du beruflich?', pt: 'O que fazes profissionalmente?', en: 'What do you do for work?' },
      { de: 'Was machst du in deiner Freizeit?', pt: 'O que fazes nos teus tempos livres?', en: 'What do you do in your free time?' },
    ],
    question: {
      de: 'Was macht Tom beruflich?',
      pt: 'O que faz o Tom profissionalmente?',
      en: 'What does Tom do for work?',
      choices: ['Er arbeitet als Ingenieur', 'Er ist Lehrer', 'Er spielt Fußball professionell', 'Er wohnt in München'],
      correctIndex: 0,
    },
  },
  {
    id: 'buergeramt',
    titleDe: 'Bürgeramt',
    titlePt: 'Registo de morada',
    titleEn: 'Registration office',
    speakerA: 'Sachbearbeiterin',
    speakerB: 'Bürger',
    lines: [
      { speaker: 'a', de: 'Guten Tag! Wie kann ich Ihnen helfen?', pt: 'Bom dia! Como posso ajudar?', en: 'Good day! How can I help you?' },
      { speaker: 'b', de: 'Ich möchte mich anmelden. Ich bin neu in Deutschland.', pt: 'Queria fazer o registo de morada. Sou novo na Alemanha.', en: "I'd like to register my address. I'm new to Germany." },
      { speaker: 'a', de: 'Haben Sie den Mietvertrag und Ihren Pass dabei?', pt: 'Tem o contrato de arrendamento e o passaporte consigo?', en: 'Do you have the rental contract and your passport with you?' },
      { speaker: 'b', de: 'Ja, hier bitte.', pt: 'Sim, aqui estão.', en: 'Yes, here you go.' },
      { speaker: 'a', de: 'Danke. Und seit wann wohnen Sie hier?', pt: 'Obrigada. E desde quando mora aqui?', en: 'Thanks. And since when have you been living here?' },
      { speaker: 'b', de: 'Seit dem ersten August.', pt: 'Desde 1 de agosto.', en: 'Since the first of August.' },
      { speaker: 'a', de: 'Alles klar, das dauert nur ein paar Minuten.', pt: 'Perfeito, demora só uns minutos.', en: 'Alright, this only takes a few minutes.' },
      { speaker: 'a', de: 'Hier ist Ihre Anmeldebestätigung. Bewahren Sie sie gut auf.', pt: 'Aqui está o seu comprovativo de registo. Guarde-o bem.', en: "Here's your registration confirmation. Keep it safe." },
      { speaker: 'b', de: 'Vielen Dank für Ihre Hilfe!', pt: 'Muito obrigado pela ajuda!', en: 'Thank you very much for your help!' },
    ],
    keyPhrases: [
      { de: 'Ich möchte mich anmelden.', pt: 'Queria fazer o registo de morada.', en: "I'd like to register my address." },
      { de: 'Haben Sie den Mietvertrag dabei?', pt: 'Tem o contrato de arrendamento consigo?', en: 'Do you have the rental contract with you?' },
      { de: 'die Anmeldebestätigung', pt: 'o comprovativo de registo', en: 'the registration confirmation' },
      { de: 'Seit wann wohnen Sie hier?', pt: 'Desde quando mora aqui?', en: 'Since when have you lived here?' },
      { de: 'Bewahren Sie es gut auf.', pt: 'Guarde-o bem.', en: 'Keep it safe.' },
    ],
    question: {
      de: 'Was braucht die Person zur Anmeldung?',
      pt: 'O que precisa a pessoa para o registo?',
      en: 'What does the person need for the registration?',
      choices: ['Mietvertrag und Pass', 'Nur den Pass', 'Eine Kreditkarte', 'Einen Führerschein'],
      correctIndex: 0,
    },
  },
]
